pod 'Parse'
pod 'ParseUI'
pod 'Bolts'
pod 'TSMessages'
pod 'Reachability'

#pod 'GoogleAnalytics-iOS-SDK', '~> 3.10'
#pod 'Appirater', '~> 2.0'
#pod 'MXGoogleAnalytics'
#pod 'Lockbox'
#pod 'AFNetworking', '~> 2.0'
#pod 'AMSmoothAlert', '~> 1.0'
#pod 'UIImage-ResizeMagick'
#pod 'SZTextView'
#pod 'APParallaxHeader'
#pod 'Block-KVO'
#pod 'FCFileManager'
#pod 'DACircularProgress'
#pod 'FCCurrentLocationGeocoder'